### ISSUE TITLE
Why. So. Slow.

### ISSUE THREAD

**Issue by farmerbean** [continuumsecurity/IriusRisk#7]
Why. d

oes comm
community.irrrrriusrisk.com
community.iriusrisk.com

loa
d every page so

slowly.

**Comment by stephendv1** [comment]
Sorry.  We're aware of the performance issues with Community but there is no quick fix.  We have made huge performance improvements in IriusRisk since version 1.8.0 (which is what Community is at).  
With our focus on getting features out to our customers, we haven't had the time to invest in bringing the Community edition up to parity with our commercial offering (currently 2.1.3).  However, that will soon change - we plan to release a version 2 of IriusRisk shortly that will bring not only performance improvements, but also diagramming to the Community edition.  
All community users will be notified of the new version once it's available.

**Comment by stephendv1** [comment]
New community was released some weeks ago with major performance and functionality improvements.  Please sign up if you'd like to try it out: https://community.iriusrisk.com
